[package]
name = "rust_ggml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi_ggml = { "path" = "../ffi_ggml" }
